const arrTracks = [
  {
    id: 0,
    trackName: "Guilt",
    trackAuthor: "Nero",
    album: "Welcome Reality",
    isliked: false,
    trackTime: "4:44",
  },
  {
    id: 1,
    trackName: "Elektro",
    trackAuthor: "Dynoro, Outwork, Mr. Gee",
    album: "Elektro",
    isliked: false,
    trackTime: "2:22",
  },
  {
    id: 2,
    trackName: "I’m Fire",
    trackAuthor: "Ali Bakgor",
    album: "I’m Fire",
    isliked: false,
    trackTime: "2:22",
  },
  {
    id: 3,
    trackName: "Non Stop",
    remix: "Remix",
    trackAuthor: "Стоункат, Psychopath",
    album: "Non Stop",
    isliked: false,
    trackTime: "4:12",
  },
  {
    id: 4,
    trackName: "Run Run",
    remix: "feat. AR/CO",
    trackAuthor: "Jaded, Will Clarke, AR/CO",
    album: "Run Run",
    isliked: false,
    trackTime: "2:54",
  },
  {
    id: 5,
    trackName: "Eyes on Fire",
    remix: "Zeds Dead Remix",
    trackAuthor: "Blue Foundation, Zeds Dead",
    album: "Eyes on Fire",
    isliked: false,
    trackTime: "5:20",
  },
  {
    id: 6,
    trackName: "Mucho Bien",
    remix: "Hi Profile Remix",
    trackAuthor: "HYBIT, Mr. Black, Offer Nissim, Hi Profile",
    album: "Mucho Bien",
    isliked: false,
    trackTime: "3:41",
  },
  {
    id: 7,
    trackName: "Knives n Cherries",
    trackAuthor: "minthaze",
    album: "Captivating",
    isliked: false,
    trackTime: "1:48",
  },
  {
    id: 8,
    trackName: "How Deep Is Your Love",
    trackAuthor: "Calvin Harris, Disciples",
    album: "How Deep Is Your Love",
    isliked: false,
    trackTime: "3:32",
  },
];
export default arrTracks;
